- set_fact: node="{{ item }}"

- name: define {{ node.key }}
  virt: name="{{ node.key }}"
        command="define"
        xml="{{ lookup('template', 'machine.xml.j2') }}"
  when: kvm_machine_state != "destroyed"
