- name: Create disk image folder {{ kvm_disk_image_folder }}
  file: path="{{ kvm_disk_image_folder }}" state=directory

- name: Create node disk images
  include: create_disks.yml
  loop_control:
    loop_var: node
  with_dict: "{{ nodes }}"
